# Generated by Django 4.2.11 on 2024-05-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0006_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_teacher',
            new_name='id_author',
        ),
        migrations.RenameField(
            model_name='videomaterials',
            old_name='discipline',
            new_name='id_discipline',
        ),
    ]
