# Generated by Django 4.2.11 on 2024-05-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0007_rename_id_teacher_comment_id_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='user',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='video',
            new_name='id_video',
        ),
    ]
