# Generated by Django 4.2.11 on 2024-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0008_rename_user_view_id_user_rename_video_view_id_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaterials',
            name='file_link',
            field=models.FileField(upload_to=''),
        ),
    ]
