# Generated by Django 4.2.11 on 2024-05-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0010_alter_videomaterials_file_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaterials',
            name='file_link',
            field=models.FileField(upload_to=''),
        ),
    ]
