# Generated by Django 4.2.11 on 2024-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0012_comment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaterials',
            name='file_link',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
