# Generated by Django 4.2.11 on 2024-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0013_alter_videomaterials_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaterials',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_previews/'),
        ),
    ]
