# Generated by Django 4.2.11 on 2024-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0014_videomaterials_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaterials',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
