# Generated by Django 4.2.11 on 2024-05-18 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0015_videomaterials_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educvideos.videomaterials')),
            ],
            options={
                'unique_together': {('id_user', 'id_video')},
            },
        ),
    ]
