# Generated by Django 4.2.11 on 2024-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0016_videolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('none', 'None')], max_length=7),
        ),
    ]
