# Generated by Django 4.2.11 on 2024-05-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0017_alter_videolike_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educvideos.discipline')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educvideos.group')),
            ],
        ),
    ]
