# Generated by Django 4.2.11 on 2024-05-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0018_groupdiscipline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupDiscipline',
        ),
    ]
