# Generated by Django 4.2.11 on 2024-05-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0018_groupdiscipline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupdiscipline',
            unique_together={('id_group', 'id_discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscipline',
            unique_together={('id_student', 'id_discipline')},
        ),
    ]
