# Generated by Django 4.2.11 on 2024-05-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0020_alter_studentdiscipline_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupdiscipline',
            unique_together={('id_group', 'id_discipline')},
        ),
    ]
