# Generated by Django 4.2.11 on 2024-05-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0021_alter_groupdiscipline_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('id_user', 'id_video')},
        ),
    ]
