# Generated by Django 4.2.11 on 2024-05-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0025_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
