# Generated by Django 4.2.11 on 2024-05-20 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educvideos', '0026_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Denied', 'Denied'), ('Deleted', 'Deleted')], default='Pending', max_length=10),
        ),
    ]
